# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_auto_20151209_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='postAdminCheck',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Proxy \u6587\u7ae0 \u5ba1\u6838 ( admin.py \u4e2d\u5feb\u6377\u52a0\u5165)',
            },
            bases=('demoapp.post',),
        ),
        migrations.CreateModel(
            name='PostProxyModel',
            fields=[
            ],
            options={
                'ordering': ['-updated_time', '-id'],
                'verbose_name': '\u6587\u7ae0\u5ba1\u6838',
                'proxy': True,
                'verbose_name_plural': 'Proxy \u6587\u7ae0\u5ba1\u6838',
            },
            bases=('demoapp.post',),
        ),
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4(\u81ea\u52a8\u7ef4\u62a4)'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='\u66f4\u65b0\u65f6\u95f4(\u81ea\u52a8\u7ef4\u62a4)'),
        ),
    ]
