# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0018_auto_20151216_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postadmincheck',
            options={'verbose_name_plural': 'Proxy \u6587\u7ae0 \u5bfc\u5165\u5bfc\u51fa ( admin.py \u4e2d\u5feb\u6377\u52a0\u5165)'},
        ),
    ]
